/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  extern GtkWidget *draw_main;
  GtkWidget *hbox1;
  GtkWidget *button_change;
  GtkWidget *button_run;
  GtkWidget *button_clear;
  extern GtkWidget *entry_option;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_window_set_title (GTK_WINDOW (window1), "SVM Toy");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  draw_main = gtk_drawing_area_new ();
  gtk_widget_ref (draw_main);
  gtk_object_set_data_full (GTK_OBJECT (window1), "draw_main", draw_main,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (draw_main);
  gtk_box_pack_start (GTK_BOX (vbox1), draw_main, TRUE, TRUE, 0);
  gtk_widget_set_usize (draw_main, 500, 475);
  gtk_widget_set_events (draw_main, GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  button_change = gtk_button_new_with_label ("Change");
  gtk_widget_ref (button_change);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button_change", button_change,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_change);
  gtk_box_pack_start (GTK_BOX (hbox1), button_change, FALSE, FALSE, 0);

  button_run = gtk_button_new_with_label ("Run");
  gtk_widget_ref (button_run);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button_run", button_run,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_run);
  gtk_box_pack_start (GTK_BOX (hbox1), button_run, FALSE, FALSE, 0);

  button_clear = gtk_button_new_with_label ("Clear");
  gtk_widget_ref (button_clear);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button_clear", button_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_clear);
  gtk_box_pack_start (GTK_BOX (hbox1), button_clear, FALSE, FALSE, 0);

  entry_option = gtk_entry_new ();
  gtk_widget_ref (entry_option);
  gtk_object_set_data_full (GTK_OBJECT (window1), "entry_option", entry_option,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_option);
  gtk_box_pack_start (GTK_BOX (hbox1), entry_option, TRUE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (window1), "destroy",
                      GTK_SIGNAL_FUNC (on_window1_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (draw_main), "button_press_event",
                      GTK_SIGNAL_FUNC (on_draw_main_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (draw_main), "expose_event",
                      GTK_SIGNAL_FUNC (on_draw_main_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_change), "clicked",
                      GTK_SIGNAL_FUNC (on_button_change_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_run), "clicked",
                      GTK_SIGNAL_FUNC (on_button_run_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_button_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_option), "activate",
                      GTK_SIGNAL_FUNC (on_button_run_clicked),
                      NULL);

  return window1;
}

